### ISSUE TITLE
Music continues to play without signing in.

### ISSUE THREAD

**Issue by parkite** [sphildreth/roadie-vuejs#14]
This is probably really a feature.  Yesterday, I was playing some music from Random Tracks. I came in this morning and went to the site. Music left from yesterday started playing. I find that interesting. So, I signed out and closed my browser. Reopened it and went to the site. Site shows me the login and I can see and hear music playing.

Honestly, not sure if this is a defect or a feature. Thought you would want to know.

![capture](https://user-images.githubusercontent.com/16633434/51749666-9a176e00-2075-11e9-8b2e-e428a1ab4a8b.png)

**Comment by sphildreth** [comment]
Resolved with beta build v20180126.1
