### ISSUE TITLE
Javascript error during Register

### ISSUE THREAD

**Issue by bruce-dunwiddie** [sphildreth/roadie-vuejs#43]
Error displayed in Developer Console when clicking Register:

_[Vue warn]: Unknown custom element: &lt;v-conainter&gt; - did you register the component correctly? For recursive components, make sure to provide the "name" option._

_found in_

_---> <Register> at src/views/Register.vue_

**Comment by bruce-dunwiddie** [comment]
https://github.com/sphildreth/roadie-vuejs/pull/44

**Comment by sphildreth** [comment]
Merged PR. Thanks.
